shop:
  playtime:
    "1": 4
    "5": 20
    "10": 40
    "20": 64

  elixir:
    type: custom-item
    cost: 64
    material: POTION
    name: "§f<§aTime §2Elixir§f>"
    lore:
      - "§7Right click to use"
      - "§cReduce 20 minutes of playtime"

time-elixir:
  material: POTION
  name: "§f<§aTime §2Elixir§f>"
  minutes: 20
  lore:
    - "§7Right click to use"
    - "§cReduce 20 minutes of playtime"
