config-version: "240725-test3"
shop:
  playtime:
    "1":
      cost: 4
      material: CLOCK
      name: "§f[§62 §fminute]"
      position: 10
      minutes: 2
      lore:
        - "§7Click to buy"
        - "§fReduce daily playtime §62 §fminute"
    "5":
      cost: 20
      material: CLOCK
      name: "§f[§610 §fminute]"
      position: 11
      minutes: 10
      lore:
        - "§7Click to buy"
        - "§fReduce daily playtime §610 §fminute"
    "10":
      cost: 40
      material: CLOCK
      name: "§f[§620 §fminutes]"
      position: 12
      minutes: 20
      lore:
        - "§7Click to buy"
        - "§fReduce daily playtime §620 §fminutes"
    "20":
      cost: 64
      material: CLOCK
      name: "§f[§640 §fminutes]"
      position: 13
      minutes: 40
      lore:
        - "§7Click to buy"
        - "§fReduce daily playtime §640 §fminutes"

  luminous-lantern:
    type: consumable
    cost: 128
    material: SOUL_LANTERN
    name: "§f<§bLuminous §9Lantern§f>"
    position: 19
    enchanted: true
    lore:
      - "§7Hold it carefully"
      - "§7Illuminate the surroundings"
      - "§7Spark of deceased soul of miner"
    effects:
      - HASTE:3600:1

  time-elixir:
    type: consumable
    cost: 64
    material: POTION
    name: "§f<§aTime §2Elixir§f>"
    position: 20
    enchanted: true
    minutes: 30
    lore:
      - "§7Drink it to use"
      - "§7Reduce §f30§7 minutes of playtime"
    effects:
      - "ABSORPTION:600:5"
      - "REGENERATION:30:1"

  playerhead:
    type: wearable
    material: PLAYER_HEAD
    cost: 32
    name: "§6Your Head"
    position: 21
    lore:
      - "§7Wear it with pride"
      - "§7Increase self confidence!"
    effects:
      - RESISTANCE:3600:1
      - LUCK:3600:1
      - GLOWING:3600:1
  
  escape-feather:
    type: on-use
    material: FEATHER
    name: "§f<§6Escape §eFeather§f>"
    position: 22
    enchanted: true
    cost: 32
    lore:
      - "§7Right click to use"
      - "§7Teleport back to your bed or world spawn."
      - "§eOnly usable in the §4Nether §eand §dEnd." 

  lava-chicken:
    type: consumable
    cost: 24
    material: COOKED_CHICKEN
    name: "§f<§cLava §6Chicken§f>"
    position: 23
    enchanted: true
    lore:
      - "§7Eat it to use"
      - "§7Grants §ffire resist §7and §fspeed"
    effects:
      - FIRE_RESISTANCE:120:1
      - SPEED:60:2

  nymph-snack:
    type: consumable
    cost: 16
    material: DRIED_KELP
    name: "§f<§bNymph's §3snack§f>"
    position: 24
    enchanted: true
    lore:
      - "§7Eat it to use"
      - "§7Grants §fwater breathing §7and §fnight vision"
    effects:
      - WATER_BREATHING:90:1
      - NIGHT_VISION:90:1

  smoke-bomb:
    type: on-use
    cost: 4
    material: FIREWORK_STAR
    name: "§f<§7Smoke §8Bomb§f>"
    position: 25
    enchanted: true
    lore:
      - "§7Right click to use"
      - "§7Grants §finvisibility §7and §fspeed"
    effects:
      - INVISIBILITY:16:1
      - SPEED:16:1
    particles:
      type: LARGE_SMOKE
      amount: 20