shop:
  playtime:
    "1": 4
    "5": 20
    "10": 40
    "20": 64

  time-elixir:
    type: consumable
    cost: 64
    material: POTION
    name: "§f<§aTime §2Elixir§f>"
    position: 21
    minutes: 20
    lore:
      - "§7Drink it to use"
      - "§7Reduce §f20§7 minutes of playtime"

  playerhead:
    cost: 32
    name: "§6Your Head"
    position: 22
    lore:
      - "§7Wear it with pride"
    effects:
      - RESISTANCE:3600:1
      - LUCK:3600:1
      - GLOWING:3600:1

  smoke-bomb:
    type: on-use
    cost: 4
    material: FIREWORK_STAR
    name: "§f<§7Smoke §8Bomb§f>"
    position: 23
    lore:
      - "§7Right click to use"
      - "§7Grants §finvisibility§7 and §fspeed"
    effects:
      - INVISIBILITY:16:1
      - SPEED:16:1
    particles:
      type: LARGE_SMOKE
      amount: 20

  nymph-snack:
    type: consumable
    cost: 64
    material: DRIED_KELP
    name: "§f<§bNymph's§3 snack§f>"
    position: 24
    lore:
      - "§7Drink it to use"
      - "§7Grants §fwater breathing and §7night vision"
    effects:
      - WATER_BREATHING:40:1
      - NIGHT_VISION:40:1