shop:
  playtime:
    "1":
      cost: 4
      material: CLOCK
      name: "§f[Reduce daily playtime §61 §fMmnute]"
      position: 10
      minutes: 1
      lore:
        - "§7Click to buy"
        - "§fCosts §c4 §fTimerald"
    "5":
      cost: 20
      material: CLOCK
      name: "§f[Reduce daily playtime §65 §fMmnutes]"
      position: 11
      minutes: 5
      lore:
        - "§7Click to buy"
        - "§fCosts §c20 §fTimerald"
    "10":
      cost: 40
      material: CLOCK
      name: "§f[Reduce daily playtime §610 §fminutes]"
      position: 12
      minutes: 10
      lore:
        - "§7Click to buy"
        - "§fCosts §c40 §fTimerald"
    "20":
      cost: 64
      material: CLOCK
      name: "§f[Reduce daily playtime §620 §fminutes]"
      position: 13
      minutes: 20
      lore:
        - "§7Click to buy"
        - "§fCosts §c64 §fTimerald"

  luminous-lantern:
    type: consumable
    cost: 128
    material: SOUL_LANTERN
    name: "§f<§bLuminous §9Lantern§f>"
    position: 20
    lore:
      - "§7Spark of deceased soul of miner"
    effects:
      - HASTE:3600:1

  time-elixir:
    type: consumable
    cost: 64
    material: POTION
    name: "§f<§aTime §2Elixir§f>"
    position: 21
    minutes: 20
    lore:
      - "§7Drink it to use"
      - "§7Reduce §f20§7 minutes of playtime"

  playerhead:
    type: wearable
    material: PLAYER_HEAD
    cost: 32
    name: "§6Your Head"
    position: 22
    lore:
      - "§7Wear it with pride"
    effects:
      - RESISTANCE:3600:1
      - LUCK:3600:1
      - GLOWING:3600:1

  nymph-snack:
    type: consumable
    cost: 16
    material: DRIED_KELP
    name: "§f<§bNymph's§3 snack§f>"
    position: 24
    lore:
      - "§7Drink it to use"
      - "§7Grants §fwater breathing and §7night vision"
    effects:
      - WATER_BREATHING:40:1
      - NIGHT_VISION:40:1

  smoke-bomb:
    type: on-use
    cost: 4
    material: FIREWORK_STAR
    name: "§f<§7Smoke §8Bomb§f>"
    position: 23
    lore:
      - "§7Right click to use"
      - "§7Grants §finvisibility§7 and §fspeed"
    effects:
      - INVISIBILITY:16:1
      - SPEED:16:1
    particles:
      type: LARGE_SMOKE
      amount: 20